package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;


@RestController    // This means that this class is a AccountsController
@RequestMapping(path = "/database") // This means URL's start with /demo (after Application path)
public class AccountsController {

    // This means to get the bean called accountsRepository
    @Autowired// Which is auto-generated by Spring, we will use it to handle the data
    private AccountsRepository accountsRepository;

    @PostMapping(path = "Accounts/add", consumes = "application/json")
    public
    String addAccounts(@RequestBody Accounts accounts) {
        accountsRepository.save(accounts);
        return "Saved";
    }

//    @RequestMapping(value = "Accounts/{ID}", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_UTF8_VALUE)
//    public
//    Accounts findAccountByAccountID(@PathVariable long ID) {
//        Accounts accounts = accountsRepository.findAccountsByID(ID);
//        return accounts;
//    }

    @RequestMapping(value = "Accounts/{accountNumber}", method = RequestMethod.POST, consumes = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public
    Accounts findAccountByAccountNumber(@PathVariable long accountNumber) {
        Accounts accounts = accountsRepository.findAccountsByAccountNumber(accountNumber);
        return accounts;
    }

//
//    @GetMapping(path = "/all")
//    public
//    @ResponseBody
//    Iterable<Accounts> getAllAccounts() {
//        // This returns a JSON or XML with the AccountsController
//        return accountsRepository.findAll();
//    }
//
//    @GetMapping(path = "/one")
//    public
//    @ResponseBody
//    Accounts findAccountByID(@PathVariable("ID") long id) {
//        return accountsRepository.findOne(id);
//    }

}
